### ISSUE TITLE
TargetClosedException after Page.CloseAsync()

### ISSUE THREAD

**Issue by siready** [kblok/puppeteer-sharp#1016]
First of all, thank you for your tremendous effort that went into this cool project!

I'm trying to generate PDF file, as you will see in the snippet below and although everything works fine, even when I fire multiple concurrent requests that are opening multiple instances of chromium, I'm seeing some exceptions in the log files.

I've been able to narrow down that the issue occurs when trying to close the connection.
The following exception is being thrown:
* ```PuppeteerSharp.TargetClosedException: 'Navigation failed because browser has disconnected! (Target.detachedFromTarget)'```

Example reproducing the issue:

```csharp
            Stream stream;
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);

            var browserOptions = new LaunchOptions
            {
                Headless = true,
                Args = new[] { "--no-sandbox" },
            };

            var browser = await Puppeteer.LaunchAsync(browserOptions, loggerFactory);
            var page = await puppeteerService.GetPage(browser);

            await page.SetContentAsync("<div>Testing</div>", puppeteerService.GetNavigationOptions());
            stream = await page.PdfStreamAsync(puppeteerService.GetPdfOptions());

            await page.CloseAsync(); // after this line the exception is thrown
            await browser.CloseAsync();
```

### Versions

PuppeteerSharp: 1.12.1
.NET: netcoreapp2.1
Platform: Windows 10

Attached log file (LogLevel.Trace): [puppeteer-sharp.log-2019-03-14.txt](https://github.com/kblok/puppeteer-sharp/files/2966308/puppeteer-sharp.log-2019-03-14.txt)

**Comment by kblok** [comment]
Hey @siready, thanks for the report. Do you have the stack trace of the exception?

**Comment by siready** [comment]
Unfortunately stack trace is not preserved. That's all I was able to get:
```at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()```

Also part of the reason why I included the log file.

**Comment by kblok** [comment]
@siready  I just created a brand new console app with the latest Puppeteer-Sharp version and it's working for me

![image](https://user-images.githubusercontent.com/2198466/55954609-853e8580-5c35-11e9-8204-9ea0eea1ca45.png)

Using Windows 10 and Core 2.1

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by R2D221** [comment]
I think I found a way to reproduce this bug. Give me a few minutes so that I can create a barebones project that throws the exception

**Comment by R2D221** [comment]
1. Create a new WPF app (I target 4.6.1, but I don't think the exact version is relevant)
2. Install PuppeteerSharp v1.18.0
3. Add the following event handler in App.xaml.cs:
    ```
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;
        }

        private void TaskScheduler_UnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs e)
        {
            // Here you can add a breakpoint or log the exception
            MessageBox.Show(e.Exception.InnerException.Message);
        }
    }
    ```
4. In the Loaded event in MainWindow, create an example where you open and close a page.
    ```
    await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
    var browser = await Puppeteer.LaunchAsync(new LaunchOptions
    {
        Headless = true
    });
    var page = await browser.NewPageAsync();
    await page.SetContentAsync("<html></html>");

    await page.CloseAsync();
    ```
5. When you run the app with the debugger attached, you'll eventually hit the breakpoint, showing the Target.detachedFromTarget error.

![image](https://user-images.githubusercontent.com/774575/61300195-272abc80-a7a7-11e9-8b10-8290fe26bc1b.png)

----

The reason I think this is happening is the following:

1. When you call CloseAsync on the page, it sends a Target.closeTarget message to the browser instance.
2. Among others, a Target.detachedFromTarget message is received.
3. The Connection then closes its CDPSession with the same message.
4. CDPSession raises a Disconnected event, which LifecycleWatcher is subscribed to.
5. LifecycleWatcher then creates a new TargetClosedException, and assigns it to an internal task.
6. The task is set to wait after a timeout (I don't know where this is set).

Since this _terminationTaskWrapper doesn't seem to be public, I don't think the end user has access to it, but in WPF we subscribed to the unobserved task exceptions event, and it seems to catch this one (since nobody is observing it).

The workaround seems to be just to filter this specific exception in the exception handler, but it would be nice if it didn't throw until we tried to do further operations with a closed page.

**Comment by kblok** [comment]
I did [some research in the past](https://github.com/kblok/puppeteer-sharp/issues/891#issuecomment-498073066) related to unobserved exceptions. But I didn't find anything I can fix there.

I would gladly review some code related to this.

**Comment by R2D221** [comment]
Thanks. I'll take a look to see what can be done.

**Comment by R2D221** [comment]
I created a pull request (https://github.com/kblok/puppeteer-sharp/pull/1218)

I think I found the issue. The problem is when disposing an object, if it has unhandled tasks, it goes to the event. So, what I did was take them and handle them myself in the finalizer.

Let me know what you think.

**Comment by Emersonbg** [comment]
I'm facing with this exception when i try page.SetContentAsync with 160.000.000 characters and many images HTML string (1555 pages PDF).

**Comment by kblok** [comment]
@Emersonbg I think that's more a limitation of the browser. That 160.000.000 characters long CDP call might be crashing the browser.

**Comment by Emersonbg** [comment]
> @Emersonbg I think that's more a limitation of the browser. That 160.000.000 characters long CDP call might be crashing the browser.

But i can save the HTML content in a .html file and the chrome open and print the HTML
