### ISSUE TITLE
Split the `PuppeteerSharp` namespace

### ISSUE THREAD

**Issue by PhenX** [kblok/puppeteer-sharp#127]
I find it difficult to browse code with 72 classes in the main namespace.
Puppeteer 1.0 has 20 files in the root (which if already a lot), I think we could at least split it into : 
 * `Exception`
 * `Options`
 * `Dto` or something like this
 * ...

**Comment by kblok** [comment]
Agreed. On the other hand, puppeteer has many files that are a bag of classes 😂 
Let me think about that when we get close to 1.0

**Comment by kblok** [comment]
This is my proposal and my idea here.

First. I don’t think that namespace are for grouping things by type but by function. So I wouldn’t by namespace like `Exception` or `Options`.
Second. You should have everything you need to use a library in the main namespace. Just by looking at the classes under `System` or [JSON.NET](https://github.com/JamesNK/Newtonsoft.Json/tree/master/Src/Newtonsoft.Json) which was taken as an example many times in this project.
So, though I think we could move some things and reorder them. I don’t think we should do much there just because “we have many files”.
These are the files I found we could move:

Namespace | Class  
-- | --
Helpers |  
  | Helper
  | MultiMap
  | HttpMethodConverter
  | TaskQueue
Input |  
  | MouseButton
Mobile |  
  | DeviceDescriptor
  | DeviceDescriptorName
  | DevicesDescriptors
  |  
Media |  
  | Clip
  | MediaType
  | MarginOptions
  | PaperFormat
  | ScreenOrientation
  | ScreenOrientationType

 Thoughts @Meir017 ?

**Comment by Meir017** [comment]
I think that the classes in the `Helpers` namespace should be internal.
The `Input`, `Mobile` and `Media` sounds good 👍
