### ISSUE TITLE
Running multiple instances concurrently

### ISSUE THREAD

**Issue by iFalcao** [kblok/puppeteer-sharp#1289]
Hello, I'm trying to execute multiple instances (between 40~60) at the same time but I've had some issues with this approach (high increase in execution time, random errors, etc).
Apart from the power of the machine, what is the best way to achieve a good performance and minimize errors from puppeteer?

There are libraries with this purpose written in javascript, like [puppeteer-cluster](https://github.com/thomasdondorf/puppeteer-cluster). I wonder if the same can be applied to .NET?

**Comment by kblok** [comment]
This is hard to answer because you might find different possible solutions. The main issue is generally chrome. Try opening 60 instances of chrome in your machine, and you will find that your computer will start burning up. Give that power to a piece of code would be killing :p 

I'd love to see a Puppeteer-Cluster for puppeteer-sharp implementation someday. In the meantime, One thing you can do is trying to reuse your browser as puppeteer-cluster does. Open one browser and then open new pages there.
I saw a few solutions where devs would open 20/30/40 pages and then build a queue. So the process X number of pages at a time. This would give you more control over chrome and your RAM.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
