### ISSUE TITLE
Support for previous .NET framework versions?

### ISSUE THREAD

**Issue by kenny-evitt** [kblok/puppeteer-sharp#307]
Based on the AppVeyor build configuration file, Puppeteer Sharp seems to only support .NET 4.7.1 (and  .NET Core 2.0).

Based on the *.nuspec* file inside the NuGet package (downloaded directly from NuGet Gallery), the package targets .NET Standard 2.0.

Are you open to supporting other versions? I wanted to use this project in a solution for which all-but-one project targeted .NET 4.0. But I also didn't have any problems updating the projects to target 4.7.1.

Also, is there a reason why the AppVeyor build configuration runs tests again `net471` and `netcoreapp2.0` but the NuGet package is created targeting `".NETStandard2.0"`? They don't seem (necessarily) equivalent based on this:

 - [Target Frameworks Reference for NuGet | Microsoft Docs](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks#supported-frameworks)

**Comment by kblok** [comment]
Puppeteer-Sharp is a multi-platform [.NET standard 2.0](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md) library. That means it can be used on any [.NET Runtime compatible with 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), .NET Framework 4.6.1+ or .NET Core 2.0+.

AppVeyor runs our unit tests, which is a multi-target library. It runs in .NET 4.7.1 and .NET Core 2.0 with the only purpose of testing the multi-platform ability of Puppeteer-Sharp. Because .NET Standard guarantees same API but not same behavior (see #90). Remember, those are the Tests' targets, not the library itself. 

So, going back to versions. Puppeteer Sharp is a .NET standard library, so that means .NET 4.5+. And there is no way we can remove the .NET Standard from the equation, because it's our bridge between .NET Framework and in .NET Core.

Being said that. If you want to see if it is possible to make it multi-target .NET Standard 2.0 and .NET Framework 4.0, using the same code and running the same tests, we could take your Pull Request into consideration. But it's not one of my motivations right now.

**Comment by kenny-evitt** [comment]
@kblok Thanks for the reply!

> If you want to see if it is possible to make it multi-target .NET Standard 2.0 and .NET Framework 4.0, using the same code and running the same tests, we could take your Pull Request into consideration. But it's not one of my motivations right now.

This is great. I definitely should have mentioned that I was willing to do this work (if you were open to it). I'll follow-up when, or if, I start working on this and have progress to report.

**Comment by kblok** [comment]
Yeah, go for it. Remember to include changes on https://github.com/kblok/puppeteer-sharp/blob/master/appveyor.yml so it tests also your new build.

**Comment by jhear1287** [comment]
I think the issue is related to Websocket, upon checking code, it uses websocket to connect to chrome. i also notice this is issue when i deploy it to  windows server 2008 r2. but when i ran it to my local machine which windows 10 there's no issues. 

You may also refer to this link.
https://msdn.microsoft.com/en-us/library/hh159285

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by csga5000** [comment]
I'd like to +1 the idea of adding separate support for non .net-standard projects.  I have some older projects I'd like to use this library on that aren't upgraded.  The one I'm working on now is 4.5 and I'm not certain how much effort it would take to upgrade to 4.6.1 or higher.
