### ISSUE TITLE
Implement CI for Linux on AppVeyor

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#429]
We already have a CI project on AppVeyor https://ci.appveyor.com/project/kblok/puppeteer-sharp-esipd.
This project is waiting for a config file `appveyor-linux.yml`.
We need a config file for linux which needs to bit similar but simpler than https://github.com/kblok/puppeteer-sharp/blob/master/appveyor.yml:

 * We don't need docfx
 * It should only have one matrix
 * It doesn't need to build docs nor publish to nuget.

We already have done some work here https://github.com/kblok/puppeteer-sharp/pull/430. So we would need to branch from that PR instead of master.

**Comment by Meir017** [comment]
@kblok AppVeyor supports Linux so it might be easier to use it then Travis

**Comment by HarpyWar** [comment]
I tried setup travis but without a success https://github.com/HarpyWar/puppeteer-sharp/commits/master

* With `netcoreapp2.0` on Linux  tests hangs up at beginning and stopped by timeout https://travis-ci.org/HarpyWar/puppeteer-sharp/jobs/432685571. I had the same behavior on my Linux machine in my program, until I installed chrome dependencies with `apt-get` https://docs.browserless.io/blog/2018/04/25/chrome-linux.html. But here it did not help. May be it's required to add `--no-sandbox` args to chrome because of running under root? But on my linux I received appropriate warning message and here not.
* On Mac `netcoreapp2.0` failed with errors https://travis-ci.org/HarpyWar/puppeteer-sharp/jobs/432685572

* With `netcoreapp2.1` both failed with error `It was not possible to find any compatible framework version` https://travis-ci.org/HarpyWar/puppeteer-sharp/jobs/432676494. I have added 2.1 target in all csproj files, may be it's required to add something else?


To activate travis-ci on the repository you have to login on https://travis-ci.org, select the project and click on activate button. Before add `.travis.yml` into the repository.

Status badge for travis can be added this way:
```
[![Build Status](https://travis-ci.org/kblok/puppeteer-sharp.svg?branch=master)](https://travis-ci.org/kblok/puppeteer-sharp)
```

**Comment by HarpyWar** [comment]
Some progress https://travis-ci.org/HarpyWar/puppeteer-sharp/builds/432858789
I get the same output in travis as on my Linux machine.

Anyone knows how to correctly run tests of puppeteer-sharp on Linux and Mac?
