### ISSUE TITLE
PuppeteerException("Response body is unavailable for redirect responses") throw outside application flow

### ISSUE THREAD

**Issue by brianfeucht** [kblok/puppeteer-sharp#891]
### Description
I'm running into an issue where Puppeteer is throwing exceptions outside of the flow of my application.  This means they are getting raised via [UnobservedTaskException](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception).  This code is running completely and a screenshot is being returned.

Is there a way I can force these exceptions to be raised in my code or a way I can suppress them?

Details of exception being thrown:
```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Response body is unavailable for redirect responses)
"errorType": "PuppeteerException",
"errorMessage": "Response body is unavailable for redirect responses"
```

### Complete minimal example reproducing the issue
```
private static readonly ScreenshotOptions screenshotOptions = new ScreenshotOptions()
{
	FullPage = true,
	Type = ScreenshotType.Png,
};

private static readonly NavigationOptions navigationOptions = new NavigationOptions
{
	WaitUntil = new[]
	{
		WaitUntilNavigation.Load,
		WaitUntilNavigation.DOMContentLoaded,
		WaitUntilNavigation.Networkidle2
	}
};
```
```
using (var browser = await browserLauncher.LaunchAsync())
using (var page = await browser.NewPageAsync())
{
	var response = await page.GoToAsync(url, navigationOptions);
	
	page.Viewport.Width = width;
	var screenshot =  await page.ScreenshotDataAsync(screenshotOptions);
	await browser.CloseAsync();
	return screenshot;
}
```
### Expected behavior:
Exceptions to be suppressed or thrown in my application context

### Actual behavior:
Exceptions bubbling up threw [UnobservedTaskException](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception) during finalization

### Versions
* Which version of PuppeteerSharp are you using?
[1.11.2](https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/blob/master/src/HeadlessChromium.Puppeteer.Lambda.Dotnet/HeadlessChromium.Puppeteer.Lambda.Dotnet.csproj#L23)
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
netcoreapp2.1 on AWS Lambda

### Additional Information
Using this library on AWS Lambda: https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet

**Comment by kblok** [comment]
That exception comes from the [NetworkManager](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/NetworkManager.cs#L319). We are just faulting the `TaskCompletionSource`.

It seems that your setup doesn't like that. I will try to see if I can listen to `TaskScheduler.UnobservedTaskException` and raise exceptions from the tests.

Is it something that is blocking you? Do you have a workaround? If it's blocking you I can release a hotfix, if not we could wait to v1.12.

Thank you for your contribution :)

**Comment by brianfeucht** [comment]
I'm not able to prevent Lambda from logging this to CloudWatch.  Their event handler fires before the one I'm registering, so all this did was create duplicate log messages.

```
TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;
private void TaskScheduler_UnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs e)
{
	e.SetObserved();
	logger.Warning(e.Exception, "Unhandled exception in lambda function");
}
```

**Comment by kblok** [comment]
@brianfeucht after some reading, there is not much we can do here to prevent this scenario.
I read in many places that using `WhenAny` can result in some Unobserved Task Exception, which is not something wrong because we don't need to observe those exceptions.

If you want to dig more on this, I would gladly review your code.
I'm able to replate this scenario running [ShouldRejectNavigationWhenBrowserCloses](https://github.com/kblok/puppeteer-sharp/pull/1152/files#diff-af1810a4ee73f85a2378002be106c2d0R53), adding a [GC.Collect](https://github.com/kblok/puppeteer-sharp/pull/1152/files#diff-af1810a4ee73f85a2378002be106c2d0R53) and [listening to UnobservedTaskException](https://github.com/kblok/puppeteer-sharp/pull/1152/files#diff-408613782162a72f6aace17be118570aR39). But there is nothing I could do on [TaskHelper.WithTimeout](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Helpers/TaskHelper.cs#L58) to prevent this.
